# Generated by Django 4.2.5 on 2023-09-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkarte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='location',
        ),
        migrations.AddField(
            model_name='box',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
